FROM mcr.microsoft.com/devcontainers/python:2-3.11-bookworm

# エラーの原因となっている古い Yarn リポジトリ設定を削除
RUN rm -f /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends libnss3-tools \
    && rm -rf /var/lib/apt/lists/*
